### ISSUE TITLE
Vancouver.XSL style not detecting

### ISSUE THREAD

**Issue by bitsrepo** [codingo/BibWord#10]
It seems like Vancouver.XSL listed in styles folder is a corrupted one. Even after copying this to \AppData\Roaming\Microsoft\Bibliography\Style for word 2016, its not getting listed in the style dropdown .  After some searching , I found that the correct style file is https://github.com/codingo/BibWord/tree/master/source/BibWord/Styles/Vancouver.XSL . So please copy this file to the https://github.com/codingo/BibWord/tree/master/styles folder

**Comment by codingo** [comment]
Resolved with #14
