### ISSUE TITLE
.exe not accessible anymore

### ISSUE THREAD

**Issue by jusdec13** [codingo/BibWord#11]
Hi,
there is a big issue now that https://archive.codeplex.com/?p=bibword is closed: I cannot find anymore the exe for the Bibword extender, which I need due to the [BO] issue...
If anybody has the .exe, could you host it here too? That would be so great !
Thank you for your help,
Jusdec

PS: I am a full noob so maybe I just made a mistake somewhere but I can't find any exe in any archives... and no manual on how to proceed for the extender installation...

**Comment by MichaSengotta** [comment]
I really need this too

**Comment by codingo** [comment]
@jusdec13 @MichaSengotta, I've  never hosted it here, but you should be able  to build it from source (all of the code can be found in this repository). The source code can be opened in visual studio community edition, which can also compile down to executable.
