### ISSUE TITLE
Correct folder on Office 365 Word for Mac 2016 

### ISSUE THREAD

**Issue by sixareen** [codingo/BibWord#2]
The documentation here suggests that style .xsl files can be put in /Library/AppSupport/Microsoft/Office365/Citations

but I have been unable to make that work here. (I have tried some obvious variants). However, I am using an edited copy of Word's own APA.xsl as a sample, not Bibword.

So can you verify from personal experience that that folder does work for Mac Word 2016?

Thanks.

**Comment by codingo** [comment]
I don't have a copy of it on hand and can't throw it into a vm but if need be I'll find somebody who has it. Did you find any pathing that would work in the end?

**Comment by sixareen** [comment]
Thanks for getting back. The one place I didn't check is the existing path within the app - putting it there used to crash Mac Word 2016, but apparently now it doesn't. At least not straight away, which is what I'd expect if the problem was a sandboxing one. So the path is

/Applications/Microsoft Word.app/Contents/Resources/Style

(i.e. in Finder, right click on /Application/Microsoft Word (or /Application/Microsoft Word.app, depending on your Finder Preferences, then click Show Package Contents to see the folders within the .app file)

I suppose it is possible that there is also somewhere *outside* the .app that works - it would certainly be handy considering how often new versions of these apps are released. If I find out anything, I'll post.

**Comment by codingo** [comment]
Awesome. Would you like to update the MakeDoc and put in a PR so you have  the credit for it? If not I'll do it tomorrow morning :)

**Comment by sixareen** [comment]
Hi codingo - if I was up to speed on git/github I'd do it, but probably better if you do it this time. Thanks for "rescuing" Yves' material, BTW.

**Comment by codingo** [comment]
No worries, I'll action it in the morning. I do hope he will pick the project back up but I'll keep it going until he does :)

**Comment by codingo** [comment]
This has now been done.
